services:
  st_okr_db:
    image: postgres:latest
    container_name: st_okr_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - st_okr_db_data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}'

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: st_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}

volumes:
  st_okr_db_data:
